//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class Stone : Block
{
	/// <summary>
	/// Gets the block type ID. Each block type must have a unique ID.
	/// </summary>
	public static int ID = 1;

	public Stone () : base ()
	{
        colorUV = new Vector2(0.05f + 0.1f,
                              0.05f + 0.1f);
	}

	public override int GetID()
	{
		return Stone.ID;
	}

	public override string ToString()
	{
		return "block stone";
	}
}


